//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlegDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.GroupCars = new HashSet<GroupCars>();
        }
    
        public int Id { get; set; }
        public int MarkId { get; set; }
        public int ModelId { get; set; }
        public string Gosnom { get; set; }
        public int SostId { get; set; }
    
        public virtual Marks Marks { get; set; }
        public virtual ModelCars ModelCars { get; set; }
        public virtual Sostoyanie Sostoyanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupCars> GroupCars { get; set; }
    }
}
