//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlegDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkersOnObjectsView
    {
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Nickname { get; set; }
        public string Post { get; set; }
        public string GunModel { get; set; }
        public string GunType { get; set; }
        public string Object { get; set; }
        public string ObjectAddress { get; set; }
        public int Id { get; set; }
    }
}
